### ISSUE TITLE
Build.gradle doesn't recognize Minecraft 1.18.1

### ISSUE THREAD

**Issue by Epicjii** [jpenilla/run-paper#11]
Caused by: java.lang.IllegalStateException: Unknown Minecraft Version: 1.18.1
	at xyz.jpenilla.runpaper.service.PaperclipService.unknownMinecraftVersion(PaperclipService.kt:302)
	at xyz.jpenilla.runpaper.service.PaperclipService.resolveLatestLocalBuild(PaperclipService.kt:229)
	at xyz.jpenilla.runpaper.service.PaperclipService.resolveBuildNumber(PaperclipService.kt:220)
	at xyz.jpenilla.runpaper.service.PaperclipService.resolvePaperclip(PaperclipService.kt:126)
	at xyz.jpenilla.runpaper.task.RunServerTask.configure(RunServerTask.kt:143)
	at xyz.jpenilla.runpaper.task.RunServerTask.exec(RunServerTask.kt:119)

**Comment by jpenilla** [comment]
not sure why this would happen, run cleanPaperclipCache and it should repair itself afterwards

**Comment by Epicjii** [comment]
Sorry I forgot to close this issue. I fixed my bug by changing my compile-only dependency to 1.18.1

**Comment by jpenilla** [comment]
Not sure how dependencies would affect this, but ok
